//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.07 at 11:12:55 AM EST 
//


package org.t3as.metamap.jaxb;

/*
 * #%L
 * NICTA t3as SNOMED service common classes
 * %%
 * Copyright (C) 2014 NICTA
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * 
 * Additional permission under GNU GPL version 3 section 7
 * 
 * If you modify this Program, or any covered work, by linking or combining
 * it with H2, GWT, or JavaBeans Activation Framework (JAF) (or a
 * modified version of those libraries), containing parts covered by the
 * terms of the H2 License, the GWT Terms, or the Common Development and
 * Distribution License (CDDL) version 1.0 ,the licensors of this Program
 * grant you additional permission to convey the resulting work.
 * #L%
 */

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aaText",
    "aaExp",
    "aaTokenNum",
    "aaLen",
    "aaExpTokenNum",
    "aaExpLen",
    "aacuIs"
})
@XmlRootElement(name = "AA")
public class AA {

    @XmlElement(name = "AAText", required = true)
    protected String aaText;
    @XmlElement(name = "AAExp", required = true)
    protected String aaExp;
    @XmlElement(name = "AATokenNum", required = true)
    protected String aaTokenNum;
    @XmlElement(name = "AALen", required = true)
    protected String aaLen;
    @XmlElement(name = "AAExpTokenNum", required = true)
    protected String aaExpTokenNum;
    @XmlElement(name = "AAExpLen", required = true)
    protected String aaExpLen;
    @XmlElement(name = "AACUIs", required = true)
    protected AACUIs aacuIs;

    /**
     * Gets the value of the aaText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAAText() {
        return aaText;
    }

    /**
     * Sets the value of the aaText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAAText(String value) {
        this.aaText = value;
    }

    /**
     * Gets the value of the aaExp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAAExp() {
        return aaExp;
    }

    /**
     * Sets the value of the aaExp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAAExp(String value) {
        this.aaExp = value;
    }

    /**
     * Gets the value of the aaTokenNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAATokenNum() {
        return aaTokenNum;
    }

    /**
     * Sets the value of the aaTokenNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAATokenNum(String value) {
        this.aaTokenNum = value;
    }

    /**
     * Gets the value of the aaLen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAALen() {
        return aaLen;
    }

    /**
     * Sets the value of the aaLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAALen(String value) {
        this.aaLen = value;
    }

    /**
     * Gets the value of the aaExpTokenNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAAExpTokenNum() {
        return aaExpTokenNum;
    }

    /**
     * Sets the value of the aaExpTokenNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAAExpTokenNum(String value) {
        this.aaExpTokenNum = value;
    }

    /**
     * Gets the value of the aaExpLen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAAExpLen() {
        return aaExpLen;
    }

    /**
     * Sets the value of the aaExpLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAAExpLen(String value) {
        this.aaExpLen = value;
    }

    /**
     * Gets the value of the aacuIs property.
     * 
     * @return
     *     possible object is
     *     {@link AACUIs }
     *     
     */
    public AACUIs getAACUIs() {
        return aacuIs;
    }

    /**
     * Sets the value of the aacuIs property.
     * 
     * @param value
     *     allowed object is
     *     {@link AACUIs }
     *     
     */
    public void setAACUIs(AACUIs value) {
        this.aacuIs = value;
    }

}
