//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.07 at 11:12:55 AM EST 
//


package org.t3as.metamap.jaxb;

/*
 * #%L
 * NICTA t3as SNOMED service common classes
 * %%
 * Copyright (C) 2014 NICTA
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * 
 * Additional permission under GNU GPL version 3 section 7
 * 
 * If you modify this Program, or any covered work, by linking or combining
 * it with H2, GWT, JUnit, or JavaBeans Activation Framework (JAF) (or a
 * modified version of those libraries), containing parts covered by the
 * terms of the H2 License, the GWT Terms, the Common Public License
 * Version 1.0, or the Common Development and Distribution License (CDDL)
 * version 1.0 ,the licensors of this Program grant you additional
 * permission to convey the resulting work.
 * #L%
 */

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "negType",
    "negTrigger",
    "negTriggerPIs",
    "negConcepts",
    "negConcPIs"
})
@XmlRootElement(name = "Negation")
public class Negation {

    @XmlElement(name = "NegType", required = true)
    protected String negType;
    @XmlElement(name = "NegTrigger", required = true)
    protected String negTrigger;
    @XmlElement(name = "NegTriggerPIs", required = true)
    protected NegTriggerPIs negTriggerPIs;
    @XmlElement(name = "NegConcepts", required = true)
    protected NegConcepts negConcepts;
    @XmlElement(name = "NegConcPIs", required = true)
    protected NegConcPIs negConcPIs;

    /**
     * Gets the value of the negType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNegType() {
        return negType;
    }

    /**
     * Sets the value of the negType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNegType(String value) {
        this.negType = value;
    }

    /**
     * Gets the value of the negTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNegTrigger() {
        return negTrigger;
    }

    /**
     * Sets the value of the negTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNegTrigger(String value) {
        this.negTrigger = value;
    }

    /**
     * Gets the value of the negTriggerPIs property.
     * 
     * @return
     *     possible object is
     *     {@link NegTriggerPIs }
     *     
     */
    public NegTriggerPIs getNegTriggerPIs() {
        return negTriggerPIs;
    }

    /**
     * Sets the value of the negTriggerPIs property.
     * 
     * @param value
     *     allowed object is
     *     {@link NegTriggerPIs }
     *     
     */
    public void setNegTriggerPIs(NegTriggerPIs value) {
        this.negTriggerPIs = value;
    }

    /**
     * Gets the value of the negConcepts property.
     * 
     * @return
     *     possible object is
     *     {@link NegConcepts }
     *     
     */
    public NegConcepts getNegConcepts() {
        return negConcepts;
    }

    /**
     * Sets the value of the negConcepts property.
     * 
     * @param value
     *     allowed object is
     *     {@link NegConcepts }
     *     
     */
    public void setNegConcepts(NegConcepts value) {
        this.negConcepts = value;
    }

    /**
     * Gets the value of the negConcPIs property.
     * 
     * @return
     *     possible object is
     *     {@link NegConcPIs }
     *     
     */
    public NegConcPIs getNegConcPIs() {
        return negConcPIs;
    }

    /**
     * Sets the value of the negConcPIs property.
     * 
     * @param value
     *     allowed object is
     *     {@link NegConcPIs }
     *     
     */
    public void setNegConcPIs(NegConcPIs value) {
        this.negConcPIs = value;
    }

}
