//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.07 at 11:12:55 AM EST 
//


package org.t3as.metamap.jaxb;

/*
 * #%L
 * MetaMap XML JAXB
 * %%
 * Copyright (C) 2014 NICTA
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * 
 * Additional permission under GNU GPL version 3 section 7
 * 
 * If you modify this Program, or any covered work, by linking or combining
 * it with H2, GWT, JUnit, or JavaBeans Activation Framework (JAF) (or a
 * modified version of those libraries), containing parts covered by the
 * terms of the H2 License, the GWT Terms, the Common Public License
 * Version 1.0, or the Common Development and Distribution License (CDDL)
 * version 1.0 ,the licensors of this Program grant you additional
 * permission to convey the resulting work.
 * #L%
 */

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.t3as.metamap.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.t3as.metamap.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SyntaxUnits }
     * 
     */
    public SyntaxUnits createSyntaxUnits() {
        return new SyntaxUnits();
    }

    /**
     * Create an instance of {@link SyntaxUnit }
     * 
     */
    public SyntaxUnit createSyntaxUnit() {
        return new SyntaxUnit();
    }

    /**
     * Create an instance of {@link Option }
     * 
     */
    public Option createOption() {
        return new Option();
    }

    /**
     * Create an instance of {@link NegTriggerPIs }
     * 
     */
    public NegTriggerPIs createNegTriggerPIs() {
        return new NegTriggerPIs();
    }

    /**
     * Create an instance of {@link NegTriggerPI }
     * 
     */
    public NegTriggerPI createNegTriggerPI() {
        return new NegTriggerPI();
    }

    /**
     * Create an instance of {@link SemTypes }
     * 
     */
    public SemTypes createSemTypes() {
        return new SemTypes();
    }

    /**
     * Create an instance of {@link SemType }
     * 
     */
    public SemType createSemType() {
        return new SemType();
    }

    /**
     * Create an instance of {@link Phrase }
     * 
     */
    public Phrase createPhrase() {
        return new Phrase();
    }

    /**
     * Create an instance of {@link Candidates }
     * 
     */
    public Candidates createCandidates() {
        return new Candidates();
    }

    /**
     * Create an instance of {@link Mappings }
     * 
     */
    public Mappings createMappings() {
        return new Mappings();
    }

    /**
     * Create an instance of {@link AACUIs }
     * 
     */
    public AACUIs createAACUIs() {
        return new AACUIs();
    }

    /**
     * Create an instance of {@link AACUI }
     * 
     */
    public AACUI createAACUI() {
        return new AACUI();
    }

    /**
     * Create an instance of {@link MatchMaps }
     * 
     */
    public MatchMaps createMatchMaps() {
        return new MatchMaps();
    }

    /**
     * Create an instance of {@link MatchMap }
     * 
     */
    public MatchMap createMatchMap() {
        return new MatchMap();
    }

    /**
     * Create an instance of {@link MatchedWord }
     * 
     */
    public MatchedWord createMatchedWord() {
        return new MatchedWord();
    }

    /**
     * Create an instance of {@link CmdLine }
     * 
     */
    public CmdLine createCmdLine() {
        return new CmdLine();
    }

    /**
     * Create an instance of {@link Options }
     * 
     */
    public Options createOptions() {
        return new Options();
    }

    /**
     * Create an instance of {@link Phrases }
     * 
     */
    public Phrases createPhrases() {
        return new Phrases();
    }

    /**
     * Create an instance of {@link Utterance }
     * 
     */
    public Utterance createUtterance() {
        return new Utterance();
    }

    /**
     * Create an instance of {@link MMOs }
     * 
     */
    public MMOs createMMOs() {
        return new MMOs();
    }

    /**
     * Create an instance of {@link MMO }
     * 
     */
    public MMO createMMO() {
        return new MMO();
    }

    /**
     * Create an instance of {@link Sources }
     * 
     */
    public Sources createSources() {
        return new Sources();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link MatchedWords }
     * 
     */
    public MatchedWords createMatchedWords() {
        return new MatchedWords();
    }

    /**
     * Create an instance of {@link Candidate }
     * 
     */
    public Candidate createCandidate() {
        return new Candidate();
    }

    /**
     * Create an instance of {@link ConceptPIs }
     * 
     */
    public ConceptPIs createConceptPIs() {
        return new ConceptPIs();
    }

    /**
     * Create an instance of {@link ConceptPI }
     * 
     */
    public ConceptPI createConceptPI() {
        return new ConceptPI();
    }

    /**
     * Create an instance of {@link AA }
     * 
     */
    public AA createAA() {
        return new AA();
    }

    /**
     * Create an instance of {@link NegConcPI }
     * 
     */
    public NegConcPI createNegConcPI() {
        return new NegConcPI();
    }

    /**
     * Create an instance of {@link Negation }
     * 
     */
    public Negation createNegation() {
        return new Negation();
    }

    /**
     * Create an instance of {@link NegConcepts }
     * 
     */
    public NegConcepts createNegConcepts() {
        return new NegConcepts();
    }

    /**
     * Create an instance of {@link NegConcPIs }
     * 
     */
    public NegConcPIs createNegConcPIs() {
        return new NegConcPIs();
    }

    /**
     * Create an instance of {@link AAs }
     * 
     */
    public AAs createAAs() {
        return new AAs();
    }

    /**
     * Create an instance of {@link Negations }
     * 
     */
    public Negations createNegations() {
        return new Negations();
    }

    /**
     * Create an instance of {@link Utterances }
     * 
     */
    public Utterances createUtterances() {
        return new Utterances();
    }

    /**
     * Create an instance of {@link NegConcept }
     * 
     */
    public NegConcept createNegConcept() {
        return new NegConcept();
    }

    /**
     * Create an instance of {@link Tokens }
     * 
     */
    public Tokens createTokens() {
        return new Tokens();
    }

    /**
     * Create an instance of {@link Token }
     * 
     */
    public Token createToken() {
        return new Token();
    }

    /**
     * Create an instance of {@link Mapping }
     * 
     */
    public Mapping createMapping() {
        return new Mapping();
    }

    /**
     * Create an instance of {@link MappingCandidates }
     * 
     */
    public MappingCandidates createMappingCandidates() {
        return new MappingCandidates();
    }

}
