//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.07 at 11:12:55 AM EST 
//


package org.t3as.metamap.jaxb;

/*
 * #%L
 * MetaMap XML JAXB
 * %%
 * Copyright (C) 2014 NICTA
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-3.0.html>.
 * 
 * Additional permission under GNU GPL version 3 section 7
 * 
 * If you modify this Program, or any covered work, by linking or combining
 * it with H2, GWT, JUnit, or JavaBeans Activation Framework (JAF) (or a
 * modified version of those libraries), containing parts covered by the
 * terms of the H2 License, the GWT Terms, the Common Public License
 * Version 1.0, or the Common Development and Distribution License (CDDL)
 * version 1.0 ,the licensors of this Program grant you additional
 * permission to convey the resulting work.
 * #L%
 */

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pmid",
    "uttSection",
    "uttNum",
    "uttText",
    "uttStartPos",
    "uttLength",
    "phrases"
})
@XmlRootElement(name = "Utterance")
public class Utterance {

    @XmlElement(name = "PMID", required = true)
    protected String pmid;
    @XmlElement(name = "UttSection", required = true)
    protected String uttSection;
    @XmlElement(name = "UttNum", required = true)
    protected String uttNum;
    @XmlElement(name = "UttText", required = true)
    protected String uttText;
    @XmlElement(name = "UttStartPos", required = true)
    protected String uttStartPos;
    @XmlElement(name = "UttLength", required = true)
    protected String uttLength;
    @XmlElement(name = "Phrases", required = true)
    protected Phrases phrases;

    /**
     * Gets the value of the pmid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPMID() {
        return pmid;
    }

    /**
     * Sets the value of the pmid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPMID(String value) {
        this.pmid = value;
    }

    /**
     * Gets the value of the uttSection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUttSection() {
        return uttSection;
    }

    /**
     * Sets the value of the uttSection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUttSection(String value) {
        this.uttSection = value;
    }

    /**
     * Gets the value of the uttNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUttNum() {
        return uttNum;
    }

    /**
     * Sets the value of the uttNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUttNum(String value) {
        this.uttNum = value;
    }

    /**
     * Gets the value of the uttText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUttText() {
        return uttText;
    }

    /**
     * Sets the value of the uttText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUttText(String value) {
        this.uttText = value;
    }

    /**
     * Gets the value of the uttStartPos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUttStartPos() {
        return uttStartPos;
    }

    /**
     * Sets the value of the uttStartPos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUttStartPos(String value) {
        this.uttStartPos = value;
    }

    /**
     * Gets the value of the uttLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUttLength() {
        return uttLength;
    }

    /**
     * Sets the value of the uttLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUttLength(String value) {
        this.uttLength = value;
    }

    /**
     * Gets the value of the phrases property.
     * 
     * @return
     *     possible object is
     *     {@link Phrases }
     *     
     */
    public Phrases getPhrases() {
        return phrases;
    }

    /**
     * Sets the value of the phrases property.
     * 
     * @param value
     *     allowed object is
     *     {@link Phrases }
     *     
     */
    public void setPhrases(Phrases value) {
        this.phrases = value;
    }

}
